name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    services:
      mongo:
        image: mongo:8.3.2-noble
        ports:
          - "27017:27017"
        volumes:
          - mongodb:/var/lib/mongodb

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
      env:
        PORT: 3000
        MONGODB_URI: mongodb://localhost:27017/myapp
